image: python:3.9.1-slim

test:
  stage: test
  script:
  - pip install -U sphinx
  - sphinx-build -b html . public
  only:
  - branches
  except:
  - master

pages:
  script:
  - pip install -r requirements.txt
  - sphinx-build -b html . public
  #- sphinx-build -d _build/doctrees . _build/html
  #- mv _build/html public
  artifacts:
    paths:
    - public
  only:
  - master
