import argparse

import numpy as np

from astropy.io import fits

import matplotlib.pyplot as plt

from kalao.cacao import toolbox
from kalao.utils import kalao_math, zernike

import kalao_config as config

# yapf: disable
additional_masked_subaps = [
    3, 4, 5, 6, 7, # Top line
    33, 44, 55, 66, 77, # Left column
    43, 54, 65, 76, 87,
    113, 114, 115, 116, 117,
    13, 23,
    19, 31,
    89, 101,
    97, 107
]
# yapf: enable


def generate_mask_from_subaps(masked_subaps, slopes):
    masked_slopes = []
    for i in sorted(set(masked_subaps)):
        masked_slopes += toolbox.subaperture_to_slopes_index(i)
    masked_slopes = np.array(masked_slopes)

    mask = np.zeros(slopes.shape, dtype=bool)
    mask[masked_slopes // slopes.shape[1],
         masked_slopes % slopes.shape[1]] = True

    return mask


def run(args):
    slopes = fits.getdata(f'{args.ncpa_folder}/slopes_median.fits')

    mask = generate_mask_from_subaps(config.AO.masked_subaps, slopes)
    mask_additional = generate_mask_from_subaps(additional_masked_subaps,
                                                slopes)

    slopes_masked = np.ma.masked_array(slopes, mask=mask | mask_additional)

    # To remove tip and tilt (done at the end too)
    # slopes_masked[0:11,0:11] -= slopes_masked[0:11,0:11].mean()
    # slopes_masked[11:22, 0:11] -= slopes_masked[11:22, 0:11].mean()

    # Generate the slopes basis
    slopes_basis = []
    for i in range(args.orders_to_fit):
        zernike_coeffs = np.zeros((args.orders_to_fit, ))
        zernike_coeffs[i] = 1

        slopes_basis.append(
                zernike.generate_slopes(zernike_coeffs,
                                        (slopes.shape[0],
                                         slopes.shape[1] // 2)))

    slopes_basis_compressed = []
    for i in range(args.orders_to_fit):
        slopes_basis_compressed.append(
                np.ma.masked_array(slopes_basis[i],
                                   mask=mask | mask_additional).compressed())
    slopes_basis_compressed = np.array(slopes_basis_compressed)

    # Drop piston term (as it's all 0s)
    slopes_basis_compressed = np.array(slopes_basis_compressed[1:])

    slopes_coeffs, residuals, rank, s = np.linalg.lstsq(
            slopes_basis_compressed.T, slopes_masked.compressed())

    # Put back piston term
    slopes_coeffs = np.concatenate([[0], slopes_coeffs])

    resulting_slopes = np.zeros(slopes.shape)
    for i in range(len(slopes_coeffs)):
        resulting_slopes += slopes_coeffs[i] * slopes_basis[i]

    # Remove tip and tilt
    slopes_coeffs[1] = 0
    slopes_coeffs[2] = 0

    resulting_slopes_no_tt = np.zeros(slopes.shape)
    for i in range(len(slopes_coeffs)):
        resulting_slopes_no_tt += slopes_coeffs[i] * slopes_basis[i]

    resulting_slopes_no_tt = np.ma.masked_array(resulting_slopes_no_tt,
                                                mask=mask, fill_value=0)

    print(f'Slopes coefficients : {slopes_coeffs}')

    # Save
    np.savetxt(f'{args.ncpa_folder}/slopes_fitted_coeffs.txt', slopes_coeffs)
    fits.PrimaryHDU(resulting_slopes_no_tt.filled()).writeto(
            f'{args.ncpa_folder}/slopes_fitted.fits', overwrite=True)

    # Display everything

    extr = np.max(np.abs(slopes))
    vmin = -extr
    vmax = extr

    plt.figure()
    plt.imshow(slopes, vmin=vmin, vmax=vmax, cmap='RdBu_r')
    plt.title("Original slopes")

    plt.figure()
    plt.imshow(slopes_masked, vmin=vmin, vmax=vmax, cmap='RdBu_r')
    plt.title("Original slopes masked")

    plt.figure()
    plt.imshow(
            np.ma.masked_array(resulting_slopes, mask=mask | mask_additional),
            vmin=vmin, vmax=vmax, cmap='RdBu_r')
    plt.title("Resulting slopes masked")

    plt.figure()
    plt.imshow(resulting_slopes, vmin=vmin, vmax=vmax, cmap='RdBu_r')
    plt.title("Resulting slopes (full)")

    plt.figure()
    plt.imshow(slopes - resulting_slopes, vmin=vmin, vmax=vmax, cmap='RdBu_r')
    plt.title("Error")

    plt.figure()
    plt.imshow(np.ma.masked_array(resulting_slopes, mask=mask), vmin=vmin,
               vmax=vmax, cmap='RdBu_r')
    plt.title("Resulting slopes (as original)")

    plt.figure()
    plt.imshow(resulting_slopes_no_tt, vmin=vmin, vmax=vmax, cmap='RdBu_r')
    plt.title("Resulting slopes (tip and tilt removed)")

    plt.show()


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
            description=
            'Fit slopes generated by open-loop NCPA optimisation to fill "bad" subapertures.'
    )
    parser.add_argument('-f', action="store", dest="ncpa_folder",
                        required=True, type=str,
                        help='Folder containing teh NCPA results')
    parser.add_argument('-o', action="store", dest="orders_to_fit", default=15,
                        type=int, help='Number of orders to fit')

    args = parser.parse_args()

    if not kalao_math.is_triangular(args.orders_to_fit):
        print("WARNING: the number of orders to fit is not triangular. Correction will be asymmetric"
              )
        print("Recommended values are 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 66, 78, 91, 105, 120"
              )

    run(args)
