import argparse
from pathlib import Path

import numpy as np

from astropy.io import fits

from kalao.utils import kmath, ktools, zernike

import matplotlib.pyplot as plt

import config

# yapf: disable
additional_masked_subaps = [
    3, 4, 5, 6, 7, # Top line
    33, 44, 55, 66, 77, # Left column
    43, 54, 65, 76, 87,
    113, 114, 115, 116, 117,
    13, 23,
    19, 31,
    89, 101,
    97, 107
]
# yapf: enable


def run(args):
    slopes = fits.getdata(args.ncpa_folder / 'slopes_median.fits')

    mask = ktools.generate_slopes_mask_from_subaps(config.WFS.masked_subaps,
                                                   slopes.shape)
    mask_additional = ktools.generate_slopes_mask_from_subaps(
        additional_masked_subaps, slopes.shape)

    slopes_coeffs = zernike.fit_slopes(slopes, args.orders_to_fit,
                                       mask | mask_additional)

    resulting_slopes = zernike.generate_slopes(slopes_coeffs, (11, 22))

    # Remove piston, tip and tilt
    slopes_coeffs[0] = 0
    slopes_coeffs[1] = 0
    slopes_coeffs[2] = 0

    resulting_slopes_no_tt = zernike.generate_slopes(slopes_coeffs, (11, 22))

    print(f'Slopes coefficients :')
    zernike.print_coeffs(slopes_coeffs)

    # Save
    np.savetxt(args.ncpa_folder / 'slopes_fitted_coeffs.txt', slopes_coeffs)
    fits.PrimaryHDU(resulting_slopes_no_tt.astype(np.float32)).writeto(
        args.ncpa_folder / 'slopes_fitted.fits', overwrite=True)

    print(f'Results written')

    # Display everything

    extrmum = np.max(np.abs(slopes))
    vmin = -extrmum
    vmax = extrmum

    plt.figure()
    plt.imshow(slopes, vmin=vmin, vmax=vmax, cmap='RdBu_r')
    plt.title("Original slopes")

    plt.figure()
    plt.imshow(np.ma.masked_array(slopes, mask=mask | mask_additional),
               vmin=vmin, vmax=vmax, cmap='RdBu_r')
    plt.title("Original slopes masked")

    plt.figure()
    plt.imshow(
        np.ma.masked_array(resulting_slopes, mask=mask | mask_additional),
        vmin=vmin, vmax=vmax, cmap='RdBu_r')
    plt.title("Resulting slopes masked")

    plt.figure()
    plt.imshow(resulting_slopes, vmin=vmin, vmax=vmax, cmap='RdBu_r')
    plt.title("Resulting slopes (full)")

    plt.figure()
    plt.imshow(slopes - resulting_slopes, vmin=vmin, vmax=vmax, cmap='RdBu_r')
    plt.title("Error")

    plt.figure()
    plt.imshow(np.ma.masked_array(resulting_slopes, mask=mask), vmin=vmin,
               vmax=vmax, cmap='RdBu_r')
    plt.title("Resulting slopes (as original)")

    plt.figure()
    plt.imshow(np.ma.masked_array(resulting_slopes_no_tt, mask=mask),
               vmin=vmin, vmax=vmax, cmap='RdBu_r')
    plt.title("Resulting slopes (tip and tilt removed)")

    plt.show()


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description=
        'Fit slopes generated by open-loop NCPA optimisation to fill "bad" subapertures.'
    )
    parser.add_argument('--folder', action="store", dest="ncpa_folder",
                        required=True, type=Path,
                        help='Folder containing the NCPA results')
    parser.add_argument('--orders', action="store", dest="orders_to_fit",
                        default=15, type=int, help='Number of orders to fit')

    args = parser.parse_args()

    if not kmath.is_triangular(args.orders_to_fit):
        print(
            '[WARNING] The number of orders to fit is not triangular. Correction will be asymmetric'
        )
        print(
            f'Recommended values are {", ".join(str(_) for _ in kmath.triangular_up_to(121))}'
        )

    run(args)
